import { useCallback, useEffect, useState } from 'react'
import axios from 'axios'
import { AddRounded, Inventory2Rounded, SearchRounded, WarningAmberRounded } from '@mui/icons-material'
import { Alert, Box, Button, Card, CardActionArea, CardContent, InputAdornment, MenuItem, Pagination, Snackbar, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../../auth/AuthContext'
import { canAccess } from '../../../auth/permissions'
import { PageHeader } from '../../../components/common/PageHeader'
import { StatCard } from '../../../components/common/StatCard'
import { UiState } from '../../../components/common/UiState'
import { formatMoney } from '../../../utils/format'
import { createInventoryItem, getInventorySummary, listInventory, type InventoryFilters } from '../api/inventory.api'
import { InventoryForm } from '../components/InventoryForm'
import { StockStatusChip } from '../components/StockStatusChip'
import type { InventoryItem, InventoryItemInput, InventoryList, InventorySummary } from '../types/inventory.types'
import { categoryLabel, inventoryCategories } from '../utils/inventoryCategories'
import '../styles/inventory.scss'

const message=(error:unknown)=>axios.isAxiosError<{message?:string}>(error)?error.response?.data?.message??'No pudimos completar la operación':'No pudimos completar la operación'
const initialList:InventoryList={items:[],total:0,page:1,pageSize:20,pages:1}
const initialSummary:InventorySummary={totalItems:0,totalUnits:0,lowStockItems:0,outOfStockItems:0,inventoryValue:0,recentMovements:[]}
export function InventoryPage(){const navigate=useNavigate();const{user}=useAuth();const canAdmin=canAccess(user,'stock:admin');const[data,setData]=useState(initialList);const[summary,setSummary]=useState(initialSummary);const[filters,setFilters]=useState<InventoryFilters>({page:1,pageSize:20,stock:'all',active:'true',sortBy:'name',order:'asc'});const[loading,setLoading]=useState(true);const[formOpen,setFormOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[list,stats]=await Promise.all([listInventory(filters),getInventorySummary()]);setData(list);setSummary(stats)}catch(e){setError(message(e))}finally{setLoading(false)}},[filters])
  useEffect(()=>{void load()},[load]);const update=<K extends keyof InventoryFilters>(key:K,value:InventoryFilters[K])=>setFilters(current=>({...current,[key]:value,page:1}));const save=async(input:InventoryItemInput)=>{setSaving(true);try{await createInventoryItem(input);setFormOpen(false);setNotice('Repuesto creado y stock inicial registrado.');await load()}catch(e){setError(message(e))}finally{setSaving(false)}}
  const card=(item:InventoryItem)=><Card key={item.id}><CardActionArea onClick={()=>navigate(`/admin/stock/${item.id}`)}><CardContent className="inventory-card"><div className="inventory-card__top"><Box><Typography fontWeight={800}>{item.name}</Typography><Typography variant="caption" color="text.secondary">{item.sku||'Sin SKU'} · {categoryLabel(item.category)}</Typography></Box><StockStatusChip item={item}/></div><Typography variant="body2" color="text.secondary">{item.compatibleModels.join(', ')||'Compatibilidad universal'}</Typography><div className="inventory-card__stock"><Typography><b>{item.currentStock}</b> unidades · mín. {item.minimumStock}</Typography><Typography fontWeight={800}>{formatMoney(item.purchaseCost)}</Typography></div></CardContent></CardActionArea></Card>
  return <Box className="inventory-page"><PageHeader eyebrow="INVENTARIO" title="Stock y repuestos" description="Existencias, costos y movimientos reales de tu negocio." action={canAdmin?<Button variant="contained" startIcon={<AddRounded/>} onClick={()=>setFormOpen(true)}>Nuevo repuesto</Button>:undefined}/>{error&&<Alert severity="error">{error}</Alert>}<div className="inventory-stats"><StatCard label="Artículos" value={String(summary.totalItems)} icon={<Inventory2Rounded/>}/><StatCard label="Stock bajo / sin stock" value={`${summary.lowStockItems} / ${summary.outOfStockItems}`} icon={<WarningAmberRounded/>} tone="warning"/><StatCard label="Valor aproximado" value={formatMoney(summary.inventoryValue)} icon={<Inventory2Rounded/>} tone="info"/></div>
  <Card><CardContent><div className="inventory-filters"><TextField size="small" placeholder="Buscar por nombre, SKU, marca o modelo" value={filters.search??''} onChange={e=>update('search',e.target.value)} InputProps={{startAdornment:<InputAdornment position="start"><SearchRounded/></InputAdornment>}}/><TextField size="small" select label="Categoría" value={filters.category??''} onChange={e=>update('category',e.target.value)}><MenuItem value="">Todas</MenuItem>{inventoryCategories.map(c=><MenuItem key={c.value} value={c.value}>{c.label}</MenuItem>)}</TextField><TextField size="small" select label="Stock" value={filters.stock} onChange={e=>update('stock',e.target.value as InventoryFilters['stock'])}><MenuItem value="all">Todo</MenuItem><MenuItem value="low">Stock bajo</MenuItem><MenuItem value="out">Sin stock</MenuItem></TextField><TextField size="small" select label="Ordenar" value={filters.sortBy} onChange={e=>update('sortBy',e.target.value as InventoryFilters['sortBy'])}><MenuItem value="name">Nombre</MenuItem><MenuItem value="stock">Stock</MenuItem><MenuItem value="updatedAt">Actualización</MenuItem></TextField></div></CardContent></Card>
  {loading?<UiState loading/>:!data.items.length?<UiState title="No hay repuestos" description="Creá el primer repuesto o modificá los filtros."/>:<><div className="inventory-mobile-list">{data.items.map(card)}</div><Card className="inventory-desktop-table"><Table><TableHead><TableRow><TableCell>SKU</TableCell><TableCell>Repuesto</TableCell><TableCell>Categoría</TableCell><TableCell>Compatibilidad</TableCell><TableCell align="right">Costo</TableCell><TableCell align="right">Precio</TableCell><TableCell align="right">Stock</TableCell><TableCell>Estado</TableCell></TableRow></TableHead><TableBody>{data.items.map(item=><TableRow hover key={item.id} sx={{cursor:'pointer'}} onClick={()=>navigate(`/admin/stock/${item.id}`)}><TableCell>{item.sku||'—'}</TableCell><TableCell><Typography fontWeight={750}>{item.name}</Typography><Typography variant="caption" color="text.secondary">{item.brand||''}</Typography></TableCell><TableCell>{categoryLabel(item.category)}</TableCell><TableCell>{item.compatibleModels.join(', ')||'Universal'}</TableCell><TableCell align="right">{formatMoney(item.purchaseCost)}</TableCell><TableCell align="right">{formatMoney(item.salePrice)}</TableCell><TableCell align="right">{item.currentStock} / {item.minimumStock}</TableCell><TableCell><StockStatusChip item={item}/></TableCell></TableRow>)}</TableBody></Table></Card></>}{data.pages>1&&<Stack alignItems="center"><Pagination page={data.page} count={data.pages} onChange={(_,page)=>setFilters(current=>({...current,page}))}/></Stack>}<InventoryForm open={formOpen} saving={saving} onClose={()=>setFormOpen(false)} onSave={save}/><Snackbar open={Boolean(notice)} autoHideDuration={4000} onClose={()=>setNotice('')} message={notice}/></Box>}
