import 'dotenv/config'
import { randomBytes } from 'node:crypto'
import { PrismaClient, PaymentMethod, type RepairStatus } from '@prisma/client'
const p=new PrismaClient(), mark='demo-cellufix-v1', email=process.env.DEMO_USER_EMAIL?.trim().toLowerCase()
const names=['Juan Pérez','Camila Gómez','Lucas Fernández','Sofía Rodríguez','Nicolás Martínez','Valentina López','Matías Sánchez','Martina Romero','Franco Díaz','Agustina Torres','Tomás Herrera','Julieta Castro','Bruno Acosta','Malena Ríos','Joaquín Medina','Emilia Suárez','Santino Molina','Delfina Cabrera']
const phones=[['Apple','iPhone 11'],['Apple','iPhone 12'],['Apple','iPhone 13'],['Apple','iPhone 13 Pro'],['Apple','iPhone 14'],['Samsung','A14'],['Samsung','A24'],['Samsung','A54'],['Samsung','S21'],['Samsung','S22'],['Motorola','Moto G32'],['Motorola','Moto G42'],['Motorola','Moto G54'],['Motorola','Edge 30'],['Xiaomi','Redmi Note 11'],['Xiaomi','Redmi Note 12'],['Xiaomi','Poco X5']]
const issues=['Cambio de módulo','Cambio de batería','Cambio de pin de carga','No enciende','Pantalla sin imagen','Problema de táctil','Daño por humedad','Falla de cámara','Parlante sin sonido','Micrófono con fallas','Software bloqueado','Reinicios constantes','Limpieza interna','Reparación de placa','Cambio de tapa trasera','Huella sin funcionar']
const statuses:RepairStatus[]=['RECEIVED','RECEIVED','REVIEW','REVIEW','REVIEW','REVIEW','BUDGET','BUDGET','APPROVED','APPROVED','APPROVED','WAITING_PART','WAITING_PART','WAITING_PART','REPAIRING','REPAIRING','REPAIRING','REPAIRING','REPAIRING','TESTING','TESTING','TESTING','READY','READY','READY','DELIVERED','DELIVERED','DELIVERED','CANCELLED','WARRANTY']
const flow:RepairStatus[]=['RECEIVED','REVIEW','BUDGET','APPROVED','WAITING_PART','REPAIRING','TESTING','READY','DELIVERED']
async function main(){
 if(!email)throw Error('DEMO_USER_EMAIL es obligatorio')
 if(process.env.NODE_ENV==='production'&&process.env.DEMO_ALLOW_PRODUCTION!=='true')throw Error('Carga demo bloqueada en producción. Definí DEMO_ALLOW_PRODUCTION=true para confirmar explícitamente')
 const u=await p.user.findUnique({where:{email},include:{business:true}});if(!u)throw Error('Usuario inexistente')
 const old=await p.client.count({where:{businessId:u.businessId,notes:{contains:mark}}});if(old){console.log(JSON.stringify({mode:'existing',user:u.name,businessId:u.businessId,clients:old}));return}
 const out=await p.$transaction(async t=>{const cs=[];for(let i=0;i<18;i++)cs.push(await t.client.create({data:{businessId:u.businessId,name:names[i],phone:`54911000${String(i).padStart(4,'0')}`,whatsapp:`54911000${String(i).padStart(4,'0')}`,email:i%3?null:`cliente${i}@example.invalid`,notes:mark,createdAt:new Date(Date.now()-(88-i*3)*864e5)}}))
 const ds=[];for(let i=0;i<25;i++){const m=phones[i%phones.length];ds.push(await t.device.create({data:{businessId:u.businessId,clientId:cs[i%18].id,brand:m[0],model:m[1],color:['Negro','Azul','Blanco'][i%3],storage:i%2?'128 GB':'256 GB',imei:i%3?`9900000000${String(i).padStart(5,'0')}`:null}}))}
 const last=await t.repair.findFirst({where:{businessId:u.businessId},orderBy:{number:'desc'}});let pay=0,hist=0,links=0
 for(let i=0;i<30;i++){const d=ds[i%25],c=cs[i%18],st=statuses[i],total=35000+(i%6)*35000;const createdAt=new Date(Date.now()-(89-i*3)*864e5),enabled=i<10&&!['DELIVERED','CANCELLED'].includes(st);const r=await t.repair.create({data:{businessId:u.businessId,number:(last?.number??1000)+i+1,clientId:c.id,deviceId:d.id,deviceBrand:d.brand,deviceModel:d.model,imei:d.imei,color:d.color,issue:issues[i%16],diagnosis:i<4?null:`Diagnóstico confirmado: ${issues[i%16].toLowerCase()}.`,physicalCondition:i%4?'Buen estado general':'Marcas leves de uso',accessories:i%3?'Sin accesorios':'Funda y cargador',notes:mark,status:st,total,partsCost:Math.floor(total*.42),laborCost:Math.floor(total*.28),trackingToken:randomBytes(32).toString('hex'),trackingEnabled:enabled,createdAt,estimatedDeliveryDate:new Date(createdAt.getTime()+7*864e5),deliveredAt:st==='DELIVERED'?new Date(createdAt.getTime()+6*864e5):null}});if(enabled)links++
  const end=st==='WARRANTY'?5:st==='CANCELLED'?1:Math.max(0,flow.indexOf(st));let prev:RepairStatus|null=null;for(let j=0;j<=end;j++){await t.repairStatusHistory.create({data:{repairId:r.id,previousStatus:prev,newStatus:flow[j],changedByUserId:u.id,createdAt:new Date(createdAt.getTime()+j*18*36e5),publicMessage:j%2?'Estamos actualizando el estado de tu equipo.':'Recibimos tu equipo correctamente.',internalNote:j%3?'Control interno realizado.':null}});prev=flow[j];hist++}
  if(i<20){const paid=st==='DELIVERED'?total:Math.floor(total*(i%3?.65:.4));for(const amount of i%5?[paid]:[Math.floor(paid/2),paid-Math.floor(paid/2)]){const method=[PaymentMethod.CASH,PaymentMethod.TRANSFER,PaymentMethod.CARD,PaymentMethod.OTHER][pay%4];await t.payment.create({data:{businessId:u.businessId,repairId:r.id,clientId:c.id,amount,method,note:method==='OTHER'?'Mercado Pago':null}});await t.cashMovement.create({data:{businessId:u.businessId,type:'INCOME',description:`Pago reparación #${r.number}`,amount,method,repairId:r.id,clientName:c.name}});pay++}await t.repair.update({where:{id:r.id},data:{paid}})}}
 return{clients:18,devices:25,repairs:30,payments:pay,history:hist,activeTrackingLinks:links}} ,{timeout:120000});console.log(JSON.stringify({mode:'created',user:u.name,businessId:u.businessId,...out},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>p.$disconnect())
