import 'dotenv/config'
import assert from 'node:assert/strict'
import jwt from 'jsonwebtoken'
import { randomUUID } from 'node:crypto'
import { prisma } from '../src/lib/prisma'

process.env.NODE_ENV = 'test'
// This integration suite exercises more writes than a human session in one minute.
process.env.RATE_LIMIT_AUTH_WRITES_MAX = '200'

async function main() {
  const { app } = await import('../src/server')
  const server = app.listen(0)
  await new Promise<void>(resolve => server.once('listening', resolve))
  const address = server.address()
  assert.ok(address && typeof address === 'object')
  const base = `http://127.0.0.1:${address.port}/api`
  const suffix = `${Date.now()}`
  const businessIds: string[] = []
  const request = async (method: string, path: string, body: object | undefined, token: string) => {
    const response = await fetch(`${base}${path}`, { method, headers: { ...(body ? { 'content-type': 'application/json' } : {}), authorization: `Bearer ${token}` }, body: body ? JSON.stringify(body) : undefined })
    return { status: response.status, body: response.headers.get('content-type')?.includes('application/json') ? await response.json() as any : await response.text() as any }
  }
  const prepareSale = async (body: { lines: Array<{ productId: string; quantity: number; expectedUnitPrice?: number }>; paymentMethod: string; expectedTotal?: number; idempotencyKey?: string }) => {
    const products = await prisma.commerceProduct.findMany({ where: { id: { in: body.lines.map(line => line.productId) } } })
    const lines = body.lines.map(line => ({ ...line, expectedUnitPrice: line.expectedUnitPrice ?? products.find(product => product.id === line.productId)!.salePrice }))
    return { ...body, lines, expectedTotal: body.expectedTotal ?? lines.reduce((total, line) => total + line.quantity * line.expectedUnitPrice, 0), idempotencyKey: body.idempotencyKey ?? randomUUID() }
  }
  const postSale = async (body: Parameters<typeof prepareSale>[0], token: string) => request('POST', '/commerce/sales', await prepareSale(body), token)
  const createTenant = async (planCode: 'INITIAL' | 'PROFESSIONAL' | 'COMPLETE') => {
    const now = new Date()
    const business = await prisma.business.create({ data: { name: `Commerce ${planCode} ${suffix}` } })
    const user = await prisma.user.create({ data: { businessId: business.id, name: 'Commerce Owner', firstName: 'Commerce', lastName: 'Owner', email: `commerce-${planCode}-${suffix}@example.com`, passwordHash: 'test', role: 'OWNER' } })
    await prisma.subscription.create({ data: { businessId: business.id, planCode, status: 'ACTIVE', trialStartedAt: now, trialEndsAt: new Date(now.getTime() - 86_400_000), trialConsumedAt: now, currentPeriodStart: now, currentPeriodEnd: new Date(now.getTime() + 30 * 86_400_000), accessExpiresAt: new Date(now.getTime() + 30 * 86_400_000) } })
    businessIds.push(business.id)
    return jwt.sign({ userId: user.id, businessId: business.id, role: user.role, platformRole: user.platformRole, tokenVersion: user.tokenVersion }, process.env.JWT_SECRET!, { expiresIn: '8h' })
  }
  try {
    const completeToken = await createTenant('COMPLETE')
    const initialToken = await createTenant('INITIAL')
    const professionalToken = await createTenant('PROFESSIONAL')
    const category = await request('POST', '/commerce/categories', { name: 'Accesorios de prueba' }, completeToken)
    assert.equal(category.status, 201)
    assert.equal((await request('GET', '/commerce/categories', undefined, completeToken)).body[0].name, 'Accesorios de prueba')
    const product = await request('POST', '/commerce/products', { name: 'Cable de prueba', category: category.body.name, purchaseCost: 1000, salePrice: 2500, currentStock: 5 }, completeToken)
    assert.equal(product.status, 201)
    const validInput = await prepareSale({ lines: [{ productId: product.body.id, quantity: 1 }], paymentMethod: 'CASH' })
    for (const missing of ['idempotencyKey', 'expectedTotal', 'expectedUnitPrice']) {
      const invalid: any = structuredClone(validInput)
      if (missing === 'expectedUnitPrice') delete invalid.lines[0].expectedUnitPrice
      else delete invalid[missing]
      assert.equal((await request('POST', '/commerce/sales', invalid, completeToken)).status, 400, `${missing} is mandatory`)
    }
    const sale = await postSale( { lines: [{ productId: product.body.id, quantity: 2 }], paymentMethod: 'CASH' }, completeToken)
    assert.equal(sale.status, 201)
    assert.equal(sale.body.total, 5000)
    assert.equal(sale.body.costOfGoodsSold, 2000)
    assert.equal(sale.body.profit, 3000)
    const updated = await prisma.commerceProduct.findUniqueOrThrow({ where: { id: product.body.id } })
    assert.equal(updated.currentStock, 3)
    const cash = await prisma.cashMovement.findFirstOrThrow({ where: { commerceSaleId: sale.body.id } })
    assert.equal(cash.origin, 'COMMERCE')
    assert.equal((await request('GET', '/commerce/products', undefined, completeToken)).body.items[0].lowStock, undefined)
    for (const origin of ['REPAIR', 'EQUIPMENT']) {
      const movement = await request('POST', '/cash/movements', { type: 'EXPENSE', description: 'Egreso de prueba', amount: 100, origin }, completeToken)
      assert.equal(movement.status, 201)
      assert.equal(movement.body.origin, origin, 'manual movements retain their structured origin')
      const filtered = await request('GET', `/cash/movements?origin=${origin}`, undefined, completeToken)
      // El egreso se cargó a mano y no tiene entidad: va a "Otros movimientos", no a la principal.
      assert.equal(filtered.body.total, 0, 'un movimiento manual no aparece en la tabla principal')
      assert.equal(filtered.body.loose.movementCount, 1, 'sí aparece en la tabla de otros movimientos')
      assert.equal(filtered.body.summary.income, 0, 'commerce sales do not enter other cash views')
      // Separarlo es sólo presentación: sigue sumando en el resumen de su propia caja.
      assert.equal(filtered.body.summary.expense, 100, 'y no deja de contar en los egresos de la caja')
      assert.equal(filtered.body.summary.totalMovements, 1, 'ni en el total de movimientos')
    }
    const commerceBox = await request('GET', '/cash/movements?origin=COMMERCE', undefined, completeToken)
    assert.equal(commerceBox.body.total, 1, 'la venta de Comercio sí está vinculada y va a la tabla principal')
    assert.equal(commerceBox.body.loose.movementCount, 0, 'y no genera movimientos manuales')
    const allBox = await request('GET', '/cash/movements', undefined, completeToken)
    assert.equal(allBox.body.total, 1, 'la vista global sólo lista lo vinculado')
    assert.equal(allBox.body.loose.movementCount, 2, 'y lleva los dos manuales a su propia tabla')
    assert.equal(allBox.body.summary.totalMovements, 3, 'el resumen sigue contando las dos tablas juntas')
    for (const token of [initialToken, professionalToken]) {
      for (const path of ['/commerce/products', '/commerce/sales', '/commerce/summary', '/commerce/categories', '/cash/movements?origin=COMMERCE']) {
        assert.equal((await request('GET', path, undefined, token)).status, 403, path)
      }
      assert.equal((await request('POST', '/cash/movements', { type: 'INCOME', origin: 'COMMERCE', description: 'Intento de acceso', amount: 100 }, token)).status, 403)
    }
    const beforeFailedSale = await prisma.commerceSale.count({ where: { businessId: businessIds[0] } })
    assert.equal((await postSale( { lines: [{ productId: product.body.id, quantity: 4 }], paymentMethod: 'CASH' }, completeToken)).status, 409)
    assert.equal(await prisma.commerceSale.count({ where: { businessId: businessIds[0] } }), beforeFailedSale)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: product.body.id } })).currentStock, 3)
    const staff = await prisma.user.create({ data: { businessId: businessIds[0], name: 'Vendedor', firstName: 'Vendedor', lastName: 'Prueba', email: `commerce-staff-${suffix}@example.com`, passwordHash: 'test', role: 'TECHNICIAN', permissions: ['commerce.view', 'commerce.sell'] } })
    const staffToken = jwt.sign({ userId: staff.id, businessId: staff.businessId, role: staff.role, platformRole: staff.platformRole, tokenVersion: staff.tokenVersion }, process.env.JWT_SECRET!, { expiresIn: '8h' })
    const legacyStaff = await prisma.user.create({ data: { businessId: businessIds[0], name: 'Técnico antiguo', email: `commerce-legacy-${suffix}@example.com`, passwordHash: 'test', role: 'TECHNICIAN' } })
    const legacyToken = jwt.sign({ userId: legacyStaff.id, businessId: legacyStaff.businessId, role: legacyStaff.role, platformRole: legacyStaff.platformRole, tokenVersion: legacyStaff.tokenVersion }, process.env.JWT_SECRET!, { expiresIn: '8h' })
    for (const permissions of [null, []]) {
      if (permissions) await prisma.user.update({ where: { id: legacyStaff.id }, data: { permissions } })
      assert.equal((await request('GET', '/commerce/products', undefined, legacyToken)).status, 403)
      assert.equal((await postSale(validInput, legacyToken)).status, 403)
      assert.equal((await request('POST', '/commerce/products', { name: 'Bloqueado' }, legacyToken)).status, 403)
    }
    const entitlements = await request('GET', '/billing/entitlements', undefined, staffToken)
    assert.equal(entitlements.status, 200)
    assert.equal(entitlements.body.commerce, true)
    assert.equal((await request('GET', '/billing/subscription', undefined, staffToken)).status, 403)
    assert.equal((await request('GET', '/commerce/products', undefined, staffToken)).status, 200)
    assert.equal((await request('POST', '/commerce/products', { name: 'No permitido' }, staffToken)).status, 403)
    await prisma.subscription.update({ where: { businessId: businessIds[1] }, data: { planCode: 'COMPLETE' } })
    assert.equal((await request('GET', '/commerce/products', undefined, initialToken)).body.total, 0)
    assert.equal((await postSale( { lines: [{ productId: product.body.id, quantity: 1 }], paymentMethod: 'CASH' }, initialToken)).status, 404)
    await prisma.subscription.update({ where: { businessId: businessIds[1] }, data: { planCode: 'INITIAL' } })
    const competingSales = await Promise.all([1, 2].map(() => postSale( { lines: [{ productId: product.body.id, quantity: 2 }], paymentMethod: 'CARD' }, staffToken)))
    assert.deepEqual(competingSales.map(result => result.status).sort(), [201, 409])
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: product.body.id } })).currentStock, 1)
    assert.equal((await request('GET', '/commerce/summary', undefined, completeToken)).body.lowStock, undefined)
    assert.equal((await postSale( { lines: [{ productId: product.body.id, quantity: 1 }, { productId: product.body.id, quantity: 1 }], paymentMethod: 'CASH' }, completeToken)).status, 409)
    assert.equal((await postSale( { lines: [{ productId: product.body.id, quantity: 0 }], paymentMethod: 'CASH' }, completeToken)).status, 400)
    assert.equal((await request('GET', '/commerce/products?pageSize=101', undefined, completeToken)).status, 400)
    assert.equal((await request('GET', '/commerce/products?inStock=invalid', undefined, completeToken)).status, 400)
    const staleEdit = { name: product.body.name, category: product.body.category, purchaseCost: 1000, salePrice: 2500, currentStock: 5, expectedStock: 5 }
    assert.equal((await request('PATCH', `/commerce/products/${product.body.id}`, staleEdit, completeToken)).status, 409, 'editing an old form must not restore sold stock')
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: product.body.id } })).currentStock, 1)
    assert.equal((await request('PATCH', `/commerce/products/${product.body.id}`, { ...staleEdit, expectedStock: 1, currentStock: 1 }, completeToken)).status, 200)
    const secondProduct = await request('POST', '/commerce/products', { name: 'Funda de prueba', category: category.body.name, purchaseCost: 2000, salePrice: 3000, currentStock: 2 }, completeToken)
    assert.equal(secondProduct.status, 201)
    const wrongTotal = await postSale( { lines: [{ productId: secondProduct.body.id, quantity: 1 }], paymentMethod: 'CASH', expectedTotal: 2500 }, completeToken)
    assert.equal(wrongTotal.status, 409, 'a stale displayed total must never be silently charged')
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: secondProduct.body.id } })).currentStock, 2)
    const multiSale = await postSale( { lines: [{ productId: product.body.id, quantity: 1 }, { productId: secondProduct.body.id, quantity: 1 }], paymentMethod: 'TRANSFER' }, completeToken)
    assert.equal(multiSale.status, 201)
    assert.equal(multiSale.body.lines.length, 2)
    assert.equal(multiSale.body.total, 5500)
    assert.equal(multiSale.body.costOfGoodsSold, 3000)
    assert.equal(multiSale.body.profit, 2500)
    const saleCount = await prisma.commerceSale.count({ where: { businessId: businessIds[0] } })
    assert.equal((await postSale( { lines: [{ productId: secondProduct.body.id, quantity: 1 }, { productId: product.body.id, quantity: 1 }], paymentMethod: 'CASH' }, completeToken)).status, 409)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: secondProduct.body.id } })).currentStock, 1)
    assert.equal(await prisma.commerceSale.count({ where: { businessId: businessIds[0] } }), saleCount)
    await prisma.commerceProduct.createMany({ data: Array.from({ length: 23 }, () => ({ businessId: businessIds[0], name: 'Producto paginado', category: category.body.name, purchaseCost: 1, salePrice: 2, currentStock: 10 })) })
    const firstPage = await request('GET', '/commerce/products?page=1&pageSize=20', undefined, completeToken)
    const secondPage = await request('GET', '/commerce/products?page=2&pageSize=20', undefined, completeToken)
    assert.equal(firstPage.body.items.length, 20)
    assert.equal(secondPage.body.items.length, 5)
    assert.equal(new Set([...firstPage.body.items, ...secondPage.body.items].map(item => item.id)).size, 25)
    assert.equal((await request('GET', '/commerce/products?search=PAGINADO', undefined, completeToken)).body.total, 23)
    const retryProduct = await prisma.commerceProduct.create({ data: { businessId: businessIds[0], name: 'Idempotencia', category: category.body.name, purchaseCost: 100, salePrice: 200, currentStock: 20 } })
    const retryInput = await prepareSale({ lines: [{ productId: retryProduct.id, quantity: 2 }], paymentMethod: 'CASH' })
    const results = await Promise.all([1, 2, 3].map(() => request('POST', '/commerce/sales', retryInput, completeToken)))
    assert.ok(results.every(result => result.status === 201), JSON.stringify(results))
    assert.equal(new Set(results.map(result => result.body.id)).size, 1, 'same key returns the same sale under concurrent requests')
    const retrySaleId = results[0].body.id
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: retryProduct.id } })).currentStock, 18)
    assert.equal(await prisma.commerceSale.count({ where: { businessId: businessIds[0], lines: { some: { productId: retryProduct.id } } } }), 1)
    assert.equal(await prisma.cashMovement.count({ where: { commerceSaleId: retrySaleId } }), 1)
    await prisma.commerceProduct.update({ where: { id: retryProduct.id }, data: { currentStock: 0, salePrice: 300 } })
    const replay = await request('POST', '/commerce/sales', retryInput, completeToken)
    assert.equal(replay.status, 201, 'replay succeeds even when stock and price have changed')
    assert.equal(replay.body.id, retrySaleId)
    assert.equal(replay.body.total, 400)
    assert.equal((await request('POST', '/commerce/sales', { ...retryInput, paymentMethod: 'CARD' }, completeToken)).status, 409, 'key cannot be reused for another payload')
    assert.equal(await prisma.cashMovement.count({ where: { commerceSaleId: retrySaleId } }), 1)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: retryProduct.id } })).currentStock, 0)
    await prisma.subscription.update({ where: { businessId: businessIds[1] }, data: { planCode: 'COMPLETE' } })
    assert.equal((await request('POST', '/commerce/sales', retryInput, initialToken)).status, 404, 'same key cannot reveal another business sale')
    const otherProduct = await prisma.commerceProduct.create({ data: { businessId: businessIds[1], name: 'Otro negocio', category: 'Test', purchaseCost: 100, salePrice: 200, currentStock: 5 } })
    const otherSale = await postSale({ ...retryInput, lines: [{ productId: otherProduct.id, quantity: 2 }] }, initialToken)
    assert.equal(otherSale.status, 201, 'same key is permitted for a different business')
    assert.notEqual(otherSale.body.id, retrySaleId)
    await prisma.subscription.update({ where: { businessId: businessIds[1] }, data: { planCode: 'INITIAL' } })
    const priceProducts = await Promise.all([200, 300].map(salePrice => prisma.commerceProduct.create({ data: { businessId: businessIds[0], name: 'Cambio compensado', category: 'Test', purchaseCost: 100, salePrice, currentStock: 5 } })))
    const stalePrices = await prepareSale({ lines: priceProducts.map(product => ({ productId: product.id, quantity: 1 })), paymentMethod: 'CASH' })
    await prisma.commerceProduct.update({ where: { id: priceProducts[0].id }, data: { salePrice: 250 } })
    await prisma.commerceProduct.update({ where: { id: priceProducts[1].id }, data: { salePrice: 250 } })
    const beforePrices = { sales: await prisma.commerceSale.count(), cash: await prisma.cashMovement.count() }
    assert.equal((await request('POST', '/commerce/sales', stalePrices, completeToken)).status, 409, 'unit price changes are rejected even with an unchanged total')
    assert.equal(await prisma.commerceSale.count(), beforePrices.sales)
    assert.equal(await prisma.cashMovement.count(), beforePrices.cash)
    assert.ok((await prisma.commerceProduct.findMany({ where: { id: { in: priceProducts.map(product => product.id) } } })).every(product => product.currentStock === 5))
    const freshPrices = await prepareSale({ ...stalePrices, lines: priceProducts.map(product => ({ productId: product.id, quantity: 1 })) })
    assert.equal((await request('POST', '/commerce/sales', freshPrices, completeToken)).status, 201, 'a rejected transaction does not consume its key')
    assert.equal((await request('GET', '/commerce/products?page=1&pageSize=20', undefined, initialToken)).status, 403)
    assert.equal((await request('POST', '/commerce/products', { name: 'Bloqueado', category: 'Test', purchaseCost: 1, salePrice: 2, currentStock: 1 }, initialToken)).status, 403)
    // Product forms no longer require or overwrite the legacy minimum stock column.
    await prisma.commerceProduct.update({ where: { id: product.body.id }, data: { minimumStock: 99 } })
    assert.equal((await request('PATCH', '/commerce/products/' + product.body.id, { ...staleEdit, expectedStock: 0, currentStock: 0 }, completeToken)).status, 200)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: product.body.id } })).minimumStock, 99)

    const audio = await request('POST', '/commerce/categories', { name: 'Audio original' }, completeToken)
    await prisma.commerceProduct.createMany({ data: Array.from({ length: 24 }, (_, i) => ({ businessId: businessIds[0], name: 'AuRi prueba ' + i, category: audio.body.name, purchaseCost: 1, salePrice: 2, currentStock: i === 0 ? 0 : 3 })) })
    const hidden = await prisma.commerceProduct.create({ data: { businessId: businessIds[0], name: 'Archivado', category: audio.body.name, purchaseCost: 1, salePrice: 2, currentStock: 3, active: false } })
    const found = await request('GET', '/commerce/products?search=auri&inStock=true&pageSize=20', undefined, completeToken)
    const foundNext = await request('GET', '/commerce/products?search=AURI&inStock=true&pageSize=20&page=2', undefined, completeToken)
    assert.equal(found.body.total, 23)
    assert.equal(found.body.items.length, 20)
    assert.equal(foundNext.body.items.length, 3)
    assert.equal(new Set([...found.body.items, ...foundNext.body.items].map(item => item.id)).size, 23)
    assert.ok(found.body.items.every(item => item.currentStock > 0))
    assert.equal((await request('GET', '/commerce/products?search=sincoincidencias&inStock=true', undefined, completeToken)).body.total, 0)
    assert.equal((await request('GET', '/commerce/products?search=auri&inStock=false', undefined, completeToken)).body.total, 24)
    assert.equal((await request('PATCH', '/commerce/categories/' + audio.body.id, { name: 'Audio nuevo' }, staffToken)).status, 403)
    assert.equal((await request('PATCH', '/commerce/categories/' + audio.body.id, { name: 'A' }, completeToken)).status, 400)
    assert.equal((await request('PATCH', '/commerce/categories/' + audio.body.id, { name: category.body.name }, completeToken)).status, 409)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: hidden.id } })).category, audio.body.name)
    const renamed = await request('PATCH', '/commerce/categories/' + audio.body.id, { name: '  Audio nuevo  ' }, completeToken)
    assert.equal(renamed.status, 200)
    assert.equal(renamed.body.name, 'Audio nuevo')
    assert.equal(renamed.body.productCount, 24)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: hidden.id } })).category, 'Audio nuevo')
    assert.equal(await prisma.commerceProduct.count({ where: { businessId: businessIds[0], category: audio.body.name } }), 0)
    assert.equal((await request('DELETE', '/commerce/categories/' + audio.body.id, undefined, completeToken)).status, 200, 'categories with products delete safely')
    assert.equal((await prisma.commerceCategory.findUniqueOrThrow({ where: { id: audio.body.id } })).active, false)
    assert.equal(await prisma.commerceProduct.count({ where: { businessId: businessIds[0], category: 'Audio nuevo', active: true } }), 0)
    const otherCategory = await prisma.commerceCategory.create({ data: { businessId: businessIds[1], name: 'Otro propietario' } })
    assert.equal((await request('PATCH', '/commerce/categories/' + otherCategory.id, { name: 'Intruso' }, completeToken)).status, 404)
    const virtual = await prisma.commerceProduct.create({ data: { businessId: businessIds[0], name: 'Legado', category: 'Categoría antigua', purchaseCost: 1, salePrice: 2, currentStock: 1 } })
    const virtualId = encodeURIComponent('product-category-Categoría antigua')
    assert.equal((await request('PATCH', '/commerce/categories/' + virtualId, { name: 'Categoría recuperada' }, completeToken)).status, 200)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: virtual.id } })).category, 'Categoría recuperada')
    assert.equal((await request('PATCH', '/commerce/categories/product-category-Inexistente', { name: 'No crear' }, completeToken)).status, 404)
    // Safe category deletion: the active catalog is cleaned while every sales/cash row survives.
    const safeCategory = await request('POST', '/commerce/categories', { name: 'Borrado seguro' }, completeToken)
    assert.equal(safeCategory.status, 201)
    const soldProduct = await prisma.commerceProduct.create({ data: { businessId: businessIds[0], name: 'Vendible seguro', category: safeCategory.body.name, purchaseCost: 1, salePrice: 3, currentStock: 5 } })
    const unsoldProduct = await prisma.commerceProduct.create({ data: { businessId: businessIds[0], name: 'Sin ventas seguro', category: safeCategory.body.name, purchaseCost: 1, salePrice: 3, currentStock: 5 } })
    const saleKey = randomUUID()
    const safeSale = await postSale({ lines: [{ productId: soldProduct.id, quantity: 2 }], paymentMethod: 'CASH', idempotencyKey: saleKey }, completeToken)
    assert.equal(safeSale.status, 201)
    const history = {
      sales: await prisma.commerceSale.count({ where: { businessId: businessIds[0] } }),
      lines: await prisma.commerceSaleLine.count({ where: { productId: soldProduct.id } }),
      cash: await prisma.cashMovement.count({ where: { businessId: businessIds[0] } }),
    }
    const otherOwned = await prisma.commerceCategory.create({ data: { businessId: businessIds[1], name: 'Ajena protegida' } })
    assert.equal((await request('DELETE', '/commerce/categories/' + otherOwned.id, undefined, completeToken)).status, 404, 'another business cannot delete a foreign category')
    assert.equal((await request('DELETE', '/commerce/categories/' + safeCategory.body.id, undefined, completeToken)).status, 200, 'deleting a category with products succeeds')
    const listedCategories = await request('GET', '/commerce/categories', undefined, completeToken)
    assert.ok(!listedCategories.body.some((row: { id: string }) => row.id === safeCategory.body.id), 'deleted category leaves the active listing')
    assert.equal((await prisma.commerceCategory.findUniqueOrThrow({ where: { id: safeCategory.body.id } })).active, false)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: soldProduct.id } })).active, false, 'sold products of the category become inactive')
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: unsoldProduct.id } })).active, false, 'unsold products of the category become inactive')
    assert.equal((await request('GET', '/commerce/products?search=seguro', undefined, completeToken)).body.total, 0, 'products of a deleted category leave the active catalog')
    assert.equal(await prisma.commerceSale.count({ where: { businessId: businessIds[0] } }), history.sales, 'sales history survives category deletion')
    assert.equal(await prisma.commerceSaleLine.count({ where: { productId: soldProduct.id } }), history.lines, 'CommerceSaleLine snapshots survive category deletion')
    assert.equal(await prisma.cashMovement.count({ where: { businessId: businessIds[0] } }), history.cash, 'CashMovement rows survive category deletion')
    const replaySafe = await postSale({ lines: [{ productId: soldProduct.id, quantity: 2 }], paymentMethod: 'CASH', idempotencyKey: saleKey }, completeToken)
    assert.equal(replaySafe.status, 201)
    assert.equal(replaySafe.body.id, safeSale.body.id, 'sale idempotency replay still works after deletion')
    const intoArchived = await request('POST', '/commerce/products', { name: 'Huerfano de seguridad', category: 'Borrado seguro', purchaseCost: 1, salePrice: 2, currentStock: 1 }, completeToken)
    assert.equal(intoArchived.status, 409, 'deleted categories cannot receive new products')
    const recreated = await request('POST', '/commerce/categories', { name: 'Borrado seguro' }, completeToken)
    assert.equal(recreated.status, 201, 'recreating a soft-deleted category reactivates it')
    assert.equal((await prisma.commerceCategory.findUniqueOrThrow({ where: { id: recreated.body.id } })).active, true)
    const reactivated = await request('POST', '/commerce/products', { name: 'Reactivado', category: 'Borrado seguro', purchaseCost: 1, salePrice: 2, currentStock: 1 }, completeToken)
    assert.equal(reactivated.status, 201, 'recreating the category allows products again')
    await prisma.commerceProduct.update({ where: { id: reactivated.body.id }, data: { active: false } })
    // Product deletion is a soft delete with or without sales history.
    const neverSold = await prisma.commerceProduct.create({ data: { businessId: businessIds[0], name: 'Borrable suave', category: category.body.name, purchaseCost: 1, salePrice: 2, currentStock: 1 } })
    assert.equal((await request('DELETE', '/commerce/products/' + neverSold.id, undefined, completeToken)).status, 200)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: neverSold.id } })).active, false, 'products without sales are kept inactive instead of deleted')
    const soldOnce = await prisma.commerceProduct.create({ data: { businessId: businessIds[0], name: 'Vendible borrable', category: category.body.name, purchaseCost: 1, salePrice: 5, currentStock: 4 } })
    const soldOnceSale = await postSale({ lines: [{ productId: soldOnce.id, quantity: 1 }], paymentMethod: 'CASH' }, completeToken)
    assert.equal(soldOnceSale.status, 201)
    const soldOnceHistory = { lines: await prisma.commerceSaleLine.count({ where: { productId: soldOnce.id } }), cash: await prisma.cashMovement.count({ where: { businessId: businessIds[0] } }) }
    assert.equal((await request('DELETE', '/commerce/products/' + soldOnce.id, undefined, completeToken)).status, 200)
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: soldOnce.id } })).active, false, 'products with sales are soft deleted')
    assert.equal(await prisma.commerceSaleLine.count({ where: { productId: soldOnce.id } }), soldOnceHistory.lines)
    assert.equal(await prisma.cashMovement.count({ where: { businessId: businessIds[0] } }), soldOnceHistory.cash)
    // Unified history must read the existing cash rows, never recreate financial data.
    const historyProduct = await prisma.commerceProduct.create({ data: { businessId: businessIds[0], name: 'Auriculares historial', category: category.body.name, purchaseCost: 30000, salePrice: 60000, currentStock: 3 } })
    const historySale = await postSale({ lines: [{ productId: historyProduct.id, quantity: 1 }], paymentMethod: 'CASH' }, completeToken)
    assert.equal(historySale.status, 201)
    const historyExpense = await request('POST', '/commerce/expenses', { description: 'Pago de cualquier cosa', amount: 50000, paymentMethod: 'TRANSFER' }, completeToken)
    assert.equal(historyExpense.status, 201)
    const historyCash = await prisma.cashMovement.findFirstOrThrow({ where: { commerceSaleId: historySale.body.id } })
    // Deliberately out of insertion order, including a tie, to exercise both sort keys.
    const future = new Date('2099-01-01T00:00:00Z')
    await prisma.cashMovement.updateMany({ where: { id: { in: [historyCash.id, historyExpense.body.id] } }, data: { createdAt: future } })
    const latestExpense = await prisma.cashMovement.create({ data: { businessId: businessIds[0], type: 'EXPENSE', origin: 'COMMERCE', description: 'Historial reciente', amount: 100, createdAt: new Date('2099-01-02T00:00:00Z') } })
    const foreignExpense = await prisma.cashMovement.create({ data: { businessId: businessIds[1], type: 'EXPENSE', origin: 'COMMERCE', description: 'Pago de cualquier cosa', amount: 999 } })
    const financialBefore = await prisma.cashMovement.findMany({ where: { businessId: businessIds[0] }, orderBy: { id: 'asc' } })
    const historyStock = (await prisma.commerceProduct.findUniqueOrThrow({ where: { id: historyProduct.id } })).currentStock
    const unified = await request('GET', '/commerce/movements?pageSize=100', undefined, completeToken)
    assert.equal(unified.status, 200, 'unified commerce history exists')
    assert.equal(unified.body.total, financialBefore.filter(row => row.origin === 'COMMERCE').length)
    assert.equal(unified.body.items[0].id, latestExpense.id, 'newest date comes first')
    assert.deepEqual(unified.body.items.slice(1, 3).map(row => row.id), [historyCash.id, historyExpense.body.id].sort().reverse(), 'ties use descending id')
    const incomeRow = unified.body.items.find(row => row.id === historyCash.id)
    assert.equal(incomeRow.type, 'INCOME')
    assert.equal(incomeRow.amount, 60000)
    assert.equal(incomeRow.commerceSale.profit, 30000)
    assert.equal(incomeRow.commerceSale.lines[0].productName, 'Auriculares historial')
    assert.equal(unified.body.items.filter(row => row.commerceSaleId === historySale.body.id).length, 1, 'sale appears once')
    const expenseRow = unified.body.items.find(row => row.id === historyExpense.body.id)
    assert.equal(expenseRow.type, 'EXPENSE')
    assert.equal(expenseRow.amount, 50000)
    assert.equal(expenseRow.commerceSale, null, 'expense has no invented sale/profit')
    assert.ok(unified.body.items.every(row => row.origin === 'COMMERCE' && row.businessId === businessIds[0]))
    assert.ok(!unified.body.items.some(row => row.id === foreignExpense.id))
    const expenseSearch = await request('GET', '/commerce/movements?search=%20PAGO%20DE%20CUALQUIER%20COSA%20&pageSize=1', undefined, completeToken)
    assert.equal(expenseSearch.body.total, 1, 'search applies to the whole tenant history')
    assert.equal(expenseSearch.body.items[0].id, historyExpense.body.id)
    const productSearch = await request('GET', '/commerce/movements?search=AURICULARES', undefined, completeToken)
    assert.equal(productSearch.body.total, 1)
    assert.equal(productSearch.body.items[0].id, historyCash.id)
    assert.equal((await request('GET', '/commerce/movements?search=' + historySale.body.id, undefined, completeToken)).body.items[0].id, historyCash.id)
    assert.equal((await request('GET', '/commerce/movements?search=sin-coincidencias-historial', undefined, completeToken)).body.total, 0)
    const unifiedFirst = await request('GET', '/commerce/movements?pageSize=2&page=1', undefined, completeToken)
    const unifiedNext = await request('GET', '/commerce/movements?pageSize=2&page=2', undefined, completeToken)
    assert.equal(unifiedFirst.body.total, unified.body.total)
    assert.equal(unifiedNext.body.pages, Math.ceil(unified.body.total / 2))
    assert.deepEqual([...unifiedFirst.body.items, ...unifiedNext.body.items].map(row => row.id), unified.body.items.slice(0, 4).map(row => row.id))
    assert.equal((await request('GET', '/commerce/movements?page=0', undefined, completeToken)).status, 400)
    assert.equal((await request('GET', '/commerce/movements?pageSize=101', undefined, completeToken)).status, 400)
    assert.equal((await request('GET', '/commerce/movements?search=' + 'x'.repeat(161), undefined, completeToken)).status, 400)
    await prisma.user.update({ where: { id: staff.id }, data: { permissions: ['commerce.view'] } })
    assert.equal((await request('GET', '/commerce/movements', undefined, staffToken)).status, 200, 'commerce.view works without cash.view')
    assert.equal((await request('GET', '/cash/movements', undefined, staffToken)).status, 403, 'cash permissions remain unchanged')
    assert.equal((await request('GET', '/commerce/movements', undefined, legacyToken)).status, 403)
    assert.equal((await request('GET', '/commerce/movements', undefined, professionalToken)).status, 403)
    assert.equal((await request('GET', '/commerce/movements', undefined, '')).status, 401)
    assert.deepEqual(await prisma.cashMovement.findMany({ where: { businessId: businessIds[0] }, orderBy: { id: 'asc' } }), financialBefore, 'history reads do not modify or duplicate cash rows')
    assert.equal((await prisma.commerceProduct.findUniqueOrThrow({ where: { id: historyProduct.id } })).currentStock, historyStock, 'history does not change stock')
    console.log('COMMERCE MOVEMENTS TEST PASSED: mixed history, search, ordering, pagination, tenant isolation, permissions, no duplicate or changed cash')
    console.log('COMMERCE TEST PASSED: acceso por plan, venta atómica, stock, costo, ganancia y caja separada')
  } finally {
    for (const businessId of businessIds) await prisma.$transaction([
      prisma.cashMovement.deleteMany({ where: { businessId } }),
      prisma.commerceSaleLine.deleteMany({ where: { sale: { businessId } } }),
      prisma.commerceSale.deleteMany({ where: { businessId } }),
      prisma.commerceProduct.deleteMany({ where: { businessId } }),
      prisma.commerceCategory.deleteMany({ where: { businessId } }),
      prisma.subscription.deleteMany({ where: { businessId } }),
      prisma.user.deleteMany({ where: { businessId } }),
      prisma.business.deleteMany({ where: { id: businessId } }),
    ])
    await prisma.$disconnect()
    await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()))
  }
}

main().catch(error => { console.error(error); process.exitCode = 1 })
