import { createHash, randomInt } from 'node:crypto'
import bcrypt from 'bcryptjs'
import { Router } from 'express'
import { rateLimit } from 'express-rate-limit'
import jwt from 'jsonwebtoken'
import { z } from 'zod'
import { prisma } from '../../lib/prisma'
import { authenticate, authOf } from '../../middlewares/auth'
import { sendPasswordChangeCode } from '../../services/email/email.service'
export const passwordChangeRouter = Router()
passwordChangeRouter.use(authenticate)
const passwordSchema = z.string().min(8).max(128).regex(/[a-z]/).regex(/[A-Z]/).regex(/\d/)
const jwtSecret = process.env.JWT_SECRET as string
const hashCode = (userId: string, code: string) => createHash('sha256').update(`${userId}:${code}`).digest('hex')
const limiter = rateLimit({ windowMs: 15 * 60_000, limit: 20, standardHeaders: 'draft-8', legacyHeaders: false, handler: (_req, res) => res.status(429).json({ success: false, message: 'Demasiados intentos. Esperá unos minutos.' }) })
const maskEmail = (email: string) => { const [name, domain] = email.split('@'); return `${name.slice(0, 3)}${'*'.repeat(Math.max(3, name.length - 3))}@${domain}` }
passwordChangeRouter.post('/request', limiter, async (req, res) => { const auth = authOf(req), user = await prisma.user.findUnique({ where: { id: auth.userId }, select: { id: true, email: true, name: true, firstName: true, isActive: true } }); if (!user?.isActive) return res.status(403).json({ success: false, message: 'No autorizado' }); const recent = await prisma.passwordResetToken.findFirst({ where: { userId: user.id, purpose: 'PASSWORD_CHANGE', usedAt: null, createdAt: { gt: new Date(Date.now() - 60_000) } }, orderBy: { createdAt: 'desc' } }); if (recent) return res.status(429).json({ success: false, message: 'Esperá antes de reenviar el código.', retryAfter: Math.max(1, Math.ceil((60_000 - (Date.now() - recent.createdAt.getTime())) / 1000)) }); const code = randomInt(100000, 1000000).toString(), now = new Date(); const token = await prisma.$transaction(async tx => { await tx.passwordResetToken.updateMany({ where: { userId: user.id, purpose: 'PASSWORD_CHANGE', usedAt: null }, data: { usedAt: now } }); return tx.passwordResetToken.create({ data: { userId: user.id, purpose: 'PASSWORD_CHANGE', tokenHash: hashCode(user.id, code), expiresAt: new Date(now.getTime() + 10 * 60_000) } }) }); try { const delivery = await sendPasswordChangeCode({ to: user.email, name: user.firstName || user.name, code, expiresInMinutes: 10 }); console.info('[mail] Password change email accepted', { emailId: delivery.id, userId: user.id }); return res.json({ success: true, maskedEmail: maskEmail(user.email), retryAfter: 60 }) } catch (error) { await prisma.passwordResetToken.update({ where: { id: token.id }, data: { usedAt: new Date() } }); console.error('[mail] Password change email rejected', { userId: user.id, reason: error instanceof Error ? error.message : 'unknown' }); return res.status(502).json({ success: false, message: 'No pudimos enviar el código. Intentá nuevamente.' }) } })
passwordChangeRouter.post('/verify', limiter, async (req, res) => { const parsed = z.object({ code: z.string().regex(/^\d{6}$/) }).strict().safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, message: 'El código ingresado no es correcto.' }); const auth = authOf(req), now = new Date(); const token = await prisma.passwordResetToken.findUnique({ where: { tokenHash: hashCode(auth.userId, parsed.data.code) } }); if (!token || token.userId !== auth.userId || token.purpose !== 'PASSWORD_CHANGE') { const active = await prisma.passwordResetToken.findFirst({ where: { userId: auth.userId, purpose: 'PASSWORD_CHANGE', usedAt: null }, orderBy: { createdAt: 'desc' } }); if (active) { const attempts = active.attempts + 1; await prisma.passwordResetToken.update({ where: { id: active.id }, data: { attempts, ...(attempts >= 5 ? { usedAt: now } : {}) } }); if (attempts >= 5) return res.status(400).json({ success: false, message: 'El código ya no es válido. Solicitá uno nuevo.' }) } return res.status(400).json({ success: false, message: 'El código ingresado no es correcto.' }) } if (token.usedAt || token.attempts >= 5) return res.status(400).json({ success: false, message: 'El código ya no es válido. Solicitá uno nuevo.' }); if (token.expiresAt <= now) return res.status(410).json({ success: false, message: 'Este código venció. Solicitá uno nuevo.' }); const consumed = await prisma.passwordResetToken.updateMany({ where: { id: token.id, usedAt: null, expiresAt: { gt: now }, attempts: { lt: 5 } }, data: { usedAt: now } }); if (consumed.count !== 1) return res.status(400).json({ success: false, message: 'El código ya no es válido. Solicitá uno nuevo.' }); return res.json({ success: true, verificationToken: jwt.sign({ purpose: 'password-change', userId: auth.userId, tokenVersion: auth.tokenVersion }, jwtSecret, { expiresIn: '10m' }) }) })
passwordChangeRouter.post('/confirm', limiter, async (req, res) => { const parsed = z.object({ verificationToken: z.string().min(1), newPassword: passwordSchema, confirmPassword: z.string().min(1) }).strict().refine(data => data.newPassword === data.confirmPassword).safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, message: 'Las contraseñas no coinciden o no cumplen los requisitos.' }); try { const payload = jwt.verify(parsed.data.verificationToken, jwtSecret) as { purpose?: string; userId?: string; tokenVersion?: number }, auth = authOf(req); if (payload.purpose !== 'password-change' || payload.userId !== auth.userId || payload.tokenVersion !== auth.tokenVersion) throw new Error('invalid'); const updated = await prisma.user.updateMany({ where: { id: auth.userId, tokenVersion: auth.tokenVersion }, data: { passwordHash: await bcrypt.hash(parsed.data.newPassword, 12), tokenVersion: { increment: 1 } } }); if (updated.count !== 1) throw new Error('used'); await prisma.passwordResetToken.updateMany({ where: { userId: auth.userId, usedAt: null }, data: { usedAt: new Date() } }); return res.json({ success: true, message: 'Contraseña actualizada correctamente.' }) } catch { return res.status(400).json({ success: false, message: 'La verificación venció. Solicitá un código nuevo.' }) } })
