import { Accordion, AccordionDetails, AccordionSummary, Button } from '@mui/material'
import { ArrowForwardRounded, CheckRounded, ExpandMoreRounded, LinkRounded, PhoneIphoneRounded, WhatsApp } from '@mui/icons-material'
import { Link } from 'react-router-dom'
import { faqs, features, workflow } from '../data/landing.data'
import { ProductMockup } from './ProductMockup'

const Heading=({tag,title,text}:{tag:string;title:string;text:string})=><div className="section-heading" data-reveal><span>{tag}</span><h2>{title}</h2><p>{text}</p></div>
export function ProblemSection(){return <section className="landing-section problem"><div className="landing-container"><Heading tag="TODO EN UN SOLO LUGAR" title="Dejá de administrar tu trabajo entre chats, papeles y memoria" text="TecnoDesk conecta la información que necesitás para trabajar con orden y responder mejor."/><div className="problem-grid">{[['Información desordenada','Presupuestos, datos y fallas repartidos entre WhatsApp, cuadernos y notas.'],['Clientes preguntando constantemente','Cada cliente puede consultar su propio seguimiento.'],['Ganancias poco claras','Registrá precios, pagos y costos para entender el movimiento.']].map(([a,b],i)=><article data-reveal key={a}><b>0{i+1}</b><h3>{a}</h3><p>{b}</p></article>)}<div className="central-flow" data-reveal>{['Cliente','Reparación','Presupuesto','Pago','Historial','Seguimiento'].map(x=><span key={x}><CheckRounded/>{x}</span>)}</div></div></div></section>}
export function FeaturesSection(){return <section id="funciones" className="landing-section tinted"><div className="landing-container"><Heading tag="FUNCIONES REALES" title="Todo lo necesario para seguir cada reparación" text="Una estructura clara desde el ingreso del celular hasta su entrega."/><div className="feature-grid">{features.map(({icon:Icon,title,text})=><article data-reveal key={title}><i><Icon/></i><h3>{title}</h3><p>{text}</p><span aria-hidden/></article>)}</div></div></section>}
export function TrackingSection(){return <section id="seguimiento" className="landing-section"><div className="landing-container"><Heading tag="SEGUIMIENTO PÚBLICO" title="Un enlace para que tu cliente sepa cómo avanza su celular" text="Actualizás el estado desde tu panel y el cliente ve únicamente la información que decidís compartir."/><div className="tracking-demo" data-reveal><div className="tech-panel"><small>PANEL DEL TÉCNICO</small><h3>Reparación #1048</h3><span className="status-pill">En reparación</span><label>Mensaje público</label><p>Tu equipo se encuentra actualmente en reparación.</p><button>Cambiar estado</button><div><LinkRounded/> Copiar enlace <WhatsApp/> WhatsApp</div></div><div className="sync-line" aria-hidden><i/></div><div className="client-panel"><small>PORTAL DEL CLIENTE</small><h3>TecnoDesk · #1048</h3><b>iPhone 13</b><div className="client-progress"><i/></div><p>En reparación</p><div><span>Total<b>$180.000</b></span><span>Pagado<b>$80.000</b></span><span>Saldo<b>$100.000</b></span></div></div></div><p className="commercial-line">Menos mensajes repetidos. Más confianza y una experiencia profesional para tu cliente.</p></div></section>}
export function WorkflowSection(){return <section id="como-funciona" className="landing-section tinted"><div className="landing-container"><Heading tag="CÓMO FUNCIONA" title="Del ingreso a la entrega, en cuatro pasos" text="Un proceso simple que acompaña la forma real de trabajar de un técnico."/><div className="workflow">{workflow.map(([n,t,x])=><article data-reveal key={n}><b>{n}</b><h3>{t}</h3><p>{x}</p></article>)}</div></div></section>}
export function PreviewBenefits(){return <><section className="landing-section preview"><div className="landing-container preview-grid"><div data-reveal><ProductMockup compact/></div><div><Heading tag="VISTA DE LA APLICACIÓN" title="La información importante, visible de un vistazo" text="Reparaciones activas, estados, pagos y accesos rápidos con navegación adaptada a cada pantalla."/><div className="preview-tabs"><button className="active">Dashboard</button><button>Reparaciones</button><button>Detalle</button><button>Seguimiento</button></div></div></div></section><section className="landing-section benefits"><div className="landing-container"><Heading tag="TRABAJÁ CON CLARIDAD" title="Más orden para vos. Mejor experiencia para tu cliente." text="TecnoDesk convierte tareas repetidas en un flujo claro y accesible."/><div className="benefit-grid">{['Encontrá cualquier reparación en segundos','Sabé qué equipos están pendientes o listos','Registrá pagos y saldos sin depender de la memoria','Dale una imagen profesional a tu servicio','Usalo desde el celular, aunque trabajes desde tu casa'].map(x=><div data-reveal key={x}><CheckRounded/><b>{x}</b></div>)}</div></div></section></>}
export function MobileComingSoon(){return <><section className="landing-section mobile-focus"><div className="landing-container mobile-grid"><div className="mini-phone" data-reveal><PhoneIphoneRounded/><b>Acciones rápidas</b>{['Nueva reparación','Cambiar estado','Registrar pago','Compartir seguimiento','Buscar cliente'].map(x=><span key={x}>{x}<ArrowForwardRounded/></span>)}</div><Heading tag="MOBILE FIRST" title="Tu servicio técnico, siempre a mano" text="TecnoDesk está pensado para técnicos que trabajan desde un local, desde su casa o en movimiento."/></div></section><section className="coming-soon"><div className="landing-container"><span>PRÓXIMAMENTE</span><div>{['Reportes avanzados','Recordatorios','Automatizaciones'].map(x=><b key={x}>{x}</b>)}</div></div></section></>}
export function FaqSection(){return <section id="preguntas" className="landing-section tinted"><div className="landing-container faq-grid"><Heading tag="PREGUNTAS FRECUENTES" title="Todo lo que necesitás saber para empezar" text="Respuestas claras sobre el uso diario de TecnoDesk."/><div>{faqs.map(([q,a])=><Accordion key={q} disableGutters><AccordionSummary expandIcon={<ExpandMoreRounded/>}>{q}</AccordionSummary><AccordionDetails>{a}</AccordionDetails></Accordion>)}</div></div></section>}
export function FinalCta(){return <section className="final-cta"><div className="landing-container"><div><span>EMPEZÁ HOY</span><h2>Organizá tu servicio técnico desde hoy</h2><p>Centralizá tus reparaciones, clientes, pagos y seguimientos en una sola plataforma.</p><Button component={Link} to="/registro" variant="contained">Crear mi cuenta</Button><Button component={Link} to="/login">Iniciar sesión</Button></div><ProductMockup compact/></div></section>}
