import { useEffect, useState, type FormEvent } from 'react'
import axios from 'axios'
import { Alert, Button, IconButton, InputAdornment, Stack, TextField, Typography } from '@mui/material'
import { VisibilityOffRounded, VisibilityRounded } from '@mui/icons-material'
import { confirmPasswordChange, requestPasswordCode, verifyPasswordCode } from './settings.api'
import { TurnstileWidget } from '../../components/security/TurnstileWidget'

const messageOf = (error: unknown, fallback: string) => axios.isAxiosError<{ message?: string; retryAfter?: number }>(error) ? error.response?.data?.message ?? fallback : fallback
export function PasswordChangeFlow({ onCompleted }: { onCompleted: () => void }) {
  const [step, setStep] = useState<'request' | 'verify' | 'password'>('request'), [maskedEmail, setMaskedEmail] = useState(''), [code, setCode] = useState(''), [proof, setProof] = useState(''), [password, setPassword] = useState(''), [confirmation, setConfirmation] = useState(''), [showPassword, setShowPassword] = useState(false), [countdown, setCountdown] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const [captchaRequired, setCaptchaRequired] = useState(false), [captchaToken, setCaptchaToken] = useState(''), [captchaResetKey, setCaptchaResetKey] = useState(0)
  useEffect(() => { if (countdown <= 0) return; const timer = window.setInterval(() => setCountdown(value => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer) }, [countdown])
  const send = async () => { if (busy || countdown > 0 || (captchaRequired && !captchaToken)) return; setBusy(true); setError(''); try { const result = await requestPasswordCode(captchaToken || undefined); setMaskedEmail(result.maskedEmail); setCountdown(result.retryAfter); setCode(''); setStep('verify'); setCaptchaRequired(false) } catch (requestError) { setError(messageOf(requestError, 'No pudimos enviar el código. Intentá nuevamente.')); if (axios.isAxiosError<{ retryAfter?: number; captchaRequired?: boolean; code?: string }>(requestError)) { setCountdown(requestError.response?.data?.retryAfter ?? 0); if (requestError.response?.data?.captchaRequired || requestError.response?.data?.code === 'TURNSTILE_REQUIRED') setCaptchaRequired(true) } } finally { if (captchaToken) { setCaptchaToken(''); setCaptchaResetKey(value => value + 1) }; setBusy(false) } }
  const verify = async (event: FormEvent) => { event.preventDefault(); if (busy) return; setBusy(true); setError(''); try { const result = await verifyPasswordCode(code); setProof(result.verificationToken); setStep('password') } catch (requestError) { setError(messageOf(requestError, 'El código ingresado no es correcto.')) } finally { setBusy(false) } }
  const confirm = async (event: FormEvent) => { event.preventDefault(); setError(''); if (password !== confirmation) return setError('Las contraseñas no coinciden.'); if (password.length < 8 || !/[a-z]/.test(password) || !/[A-Z]/.test(password) || !/\d/.test(password)) return setError('Usá al menos 8 caracteres, una mayúscula, una minúscula y un número.'); setBusy(true); try { await confirmPasswordChange(proof, password, confirmation); onCompleted() } catch (requestError) { setError(messageOf(requestError, 'No pudimos cambiar la contraseña.')) } finally { setBusy(false) } }
  const visibility = <InputAdornment position="end"><IconButton onClick={() => setShowPassword(value => !value)} aria-label={showPassword ? 'Ocultar contraseña' : 'Mostrar contraseña'}>{showPassword ? <VisibilityOffRounded /> : <VisibilityRounded />}</IconButton></InputAdornment>
  return <Stack spacing={2}>{error && <Alert severity="error">{error}</Alert>}{step === 'request' && <><Typography color="text.secondary">Por seguridad enviaremos un código de seis dígitos al correo de tu cuenta.</Typography>{captchaRequired && <TurnstileWidget onToken={setCaptchaToken} resetKey={captchaResetKey} />}<Button variant="contained" onClick={() => void send()} disabled={busy || (captchaRequired && !captchaToken)}>{busy ? 'Enviando…' : 'Enviar código'}</Button></>}{step === 'verify' && <Stack component="form" spacing={2} onSubmit={verify}><Alert severity="success">Enviamos un código de seguridad a {maskedEmail}.</Alert><TextField label="Código de verificación" value={code} onChange={event => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))} inputProps={{ inputMode: 'numeric', maxLength: 6 }} /><Button type="submit" variant="contained" disabled={busy || code.length !== 6}>Verificar código</Button><Button onClick={() => void send()} disabled={busy || countdown > 0}>{countdown > 0 ? `Reenviar código en ${countdown} s` : 'Reenviar código'}</Button></Stack>}{step === 'password' && <Stack component="form" spacing={2} onSubmit={confirm}><Alert severity="success">Código verificado correctamente.</Alert><TextField type={showPassword ? 'text' : 'password'} label="Nueva contraseña" value={password} onChange={event => setPassword(event.target.value)} helperText="Mínimo 8 caracteres, mayúscula, minúscula y número." InputProps={{ endAdornment: visibility }} /><TextField type={showPassword ? 'text' : 'password'} label="Confirmar contraseña" value={confirmation} onChange={event => setConfirmation(event.target.value)} InputProps={{ endAdornment: visibility }} /><Button type="submit" variant="contained" disabled={busy || !password || !confirmation}>{busy ? 'Cambiando…' : 'Cambiar contraseña'}</Button></Stack>}</Stack>
}
