import { useEffect, useState } from 'react'
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, Stack, Tab, Tabs, TextField, Typography } from '@mui/material'
import { approveAdminPayment, getAdminDashboard, getAdminPayments, getAdminSubscriptions, getBillingSettings, rejectAdminPayment, saveBillingSettings } from './platformAdmin.api'
import { formatARS, formatDate } from '../billing/billing.utils'
import './platform-admin.scss'
type Dashboard={clients:number;active:number;trials:number;pendingPayments:number;grace:number;suspended:number;estimatedMrrARS:number}
export function PlatformAdminPage(){const[dash,setDash]=useState<Dashboard|null>(null);const[subscriptions,setSubscriptions]=useState<any[]>([]);const[payments,setPayments]=useState<any[]>([]);const[tab,setTab]=useState('PENDING');const[rejectId,setRejectId]=useState<string|null>(null);const[reason,setReason]=useState('');const[settings,setSettings]=useState({holderName:'',bankName:'',alias:'',cbuCvu:'',taxId:'',additionalText:''});const[msg,setMsg]=useState('');
const load=async()=>{const[d,s,p,b]=await Promise.all([getAdminDashboard(),getAdminSubscriptions(),getAdminPayments(tab),getBillingSettings()]);setDash(d);setSubscriptions(s);setPayments(p);if(b)setSettings({holderName:b.holderName??'',bankName:b.bankName??'',alias:b.alias??'',cbuCvu:b.cbuCvu??'',taxId:b.taxId??'',additionalText:b.additionalText??''})};useEffect(()=>{void load()},[tab]);
const approve=async(id:string)=>{if(!window.confirm('¿Confirmar este pago y activar la suscripción?'))return;await approveAdminPayment(id);setMsg('Pago aprobado correctamente.');await load()};const reject=async()=>{if(!rejectId)return;await rejectAdminPayment(rejectId,reason);setRejectId(null);setReason('');setMsg('Pago rechazado.');await load()};const save=async()=>{await saveBillingSettings(settings);setMsg('Datos bancarios guardados.')};
return <Box className="platform-admin"><Box><Typography variant="overline" color="primary" fontWeight={900}>SUPER ADMIN</Typography><Typography variant="h4" fontWeight={900}>Administración de TecnoDesk</Typography></Box>{msg&&<Alert severity="success">{msg}</Alert>}{dash&&<section className="platform-metrics">{[['Clientes',dash.clients],['Activos',dash.active],['En prueba',dash.trials],['Pagos pendientes',dash.pendingPayments],['En gracia',dash.grace],['Suspendidos',dash.suspended],['MRR estimado',formatARS(dash.estimatedMrrARS)]].map(([label,value])=><article key={String(label)}><small>{label}</small><strong>{value}</strong></article>)}</section>}
<section className="platform-panel"><Typography variant="h6" fontWeight={900}>Clientes TecnoDesk</Typography><div className="platform-table"><table><thead><tr><th>Negocio</th><th>Propietario</th><th>Plan</th><th>Estado</th><th>Vencimiento</th><th>Último pago</th></tr></thead><tbody>{subscriptions.map(row=><tr key={row.id}><td>{row.business.name}</td><td>{row.business.users[0]?.email??'—'}</td><td>{row.plan.name}</td><td>{row.status}</td><td>{formatDate(row.status==='TRIALING'?row.trialEndsAt:row.currentPeriodEnd)}</td><td>{formatDate(row.payments[0]?.reviewedAt)}</td></tr>)}</tbody></table></div></section>
<section className="platform-panel"><Typography variant="h6" fontWeight={900}>Pagos</Typography><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable"><Tab value="PENDING" label="Pendientes"/><Tab value="APPROVED" label="Aprobados"/><Tab value="REJECTED" label="Rechazados"/></Tabs><div className="platform-payments">{payments.map(payment=><article key={payment.id}><div><b>{payment.business.name} · {payment.plan.name}</b><Typography variant="body2">Esperado {formatARS(payment.expectedAmount)} · Informado {formatARS(payment.reportedAmount)}</Typography><Typography variant="caption">{payment.payerName} · {formatDate(payment.transferDate)} · {payment.reference||'Sin referencia'}</Typography></div>{payment.status==='PENDING'&&<Stack direction="row" spacing={1}><Button onClick={()=>setRejectId(payment.id)} color="error">Rechazar</Button><Button variant="contained" onClick={()=>void approve(payment.id)}>Aprobar</Button></Stack>}</article>)}</div></section>
<section className="platform-panel"><Typography variant="h6" fontWeight={900}>Configuración · Cobros</Typography><Box display="grid" gridTemplateColumns={{xs:'1fr',md:'1fr 1fr'}} gap={2} mt={2}>{Object.entries(settings).map(([key,value])=><TextField key={key} label={({holderName:'Titular',bankName:'Banco',alias:'Alias',cbuCvu:'CBU/CVU',taxId:'CUIT',additionalText:'Texto adicional'} as Record<string,string>)[key]} multiline={key==='additionalText'} value={value??''} onChange={e=>setSettings({...settings,[key]:e.target.value})}/>)}</Box><Button variant="contained" sx={{mt:2}} onClick={()=>void save()}>Guardar</Button></section>
<Dialog open={Boolean(rejectId)} onClose={()=>setRejectId(null)} fullWidth maxWidth="xs"><DialogTitle>Rechazar pago</DialogTitle><DialogContent><TextField autoFocus fullWidth multiline minRows={3} label="Motivo del rechazo" value={reason} onChange={e=>setReason(e.target.value)} sx={{mt:1}}/></DialogContent><DialogActions><Button onClick={()=>setRejectId(null)}>Cancelar</Button><Button color="error" variant="contained" disabled={reason.trim().length<3} onClick={()=>void reject()}>Rechazar</Button></DialogActions></Dialog>
</Box>}
