import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Box, Button, Card, CardContent, Grid, Stack, Typography } from '@mui/material'
import { AddRounded, ArrowBackRounded, ArrowForwardRounded, PaymentsRounded, ReceiptLongRounded, WalletRounded } from '@mui/icons-material'
import { PageHeader } from '../components/common/PageHeader'
import { StatCard } from '../components/common/StatCard'
import { StatusChip } from '../components/common/StatusChip'
import { UiState } from '../components/common/UiState'
import { getClient, updateClient, type ClientRecord } from '../services/operations'
import { formatDate, formatMoney } from '../utils/format'
import type { RepairStatus } from '../types'

const apiStatus:Record<string,RepairStatus>={RECEIVED:'received',REVIEW:'review',BUDGET:'budget',APPROVED:'approved',WAITING_PART:'waiting_part',REPAIRING:'repairing',TESTING:'testing',READY:'ready',DELIVERED:'delivered',CANCELLED:'cancelled',WARRANTY:'warranty'}
export function ClientDetailPage(){
 const{id}=useParams(),navigate=useNavigate();const[client,setClient]=useState<ClientRecord|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false)
 const load=useCallback(async()=>{if(!id)return;setLoading(true);setError(false);try{setClient(await getClient(id))}catch{setError(true)}finally{setLoading(false)}},[id]);useEffect(()=>{void load()},[load])
 if(loading)return <Card><UiState loading/></Card>;if(error||!client)return <Card><UiState title="Cliente no encontrado" description="No pudimos cargar los datos del cliente." action={()=>void load()}/></Card>
 const paid=client.repairs.reduce((sum,item)=>sum+item.paid,0),pending=client.repairs.reduce((sum,item)=>sum+Math.max(0,item.total-item.paid),0),newest=client.repairs[0]?.createdAt,newRepair=`/admin/reparaciones?new=1&clientId=${encodeURIComponent(client.id)}`
 const edit=async()=>{const name=window.prompt('Nombre del cliente',client.name)?.trim();if(!name)return;const phone=window.prompt('Teléfono del cliente',client.phone??'');await updateClient(client.id,{name,phone:phone?.trim()||null});await load()}
 return <Box><Button startIcon={<ArrowBackRounded/>} onClick={()=>navigate('/admin/clientes')} sx={{mb:1}}>Volver</Button><PageHeader eyebrow="DETALLE DE CLIENTE" title={client.name} description={`${client.phone||'Sin teléfono'} · Cliente desde ${formatDate(client.createdAt)}`} action={<Stack direction="row" gap={1}><Button onClick={()=>void edit()}>Editar</Button><Button variant="contained" startIcon={<AddRounded/>} onClick={()=>navigate(newRepair)}>Nueva reparación</Button></Stack>}/>
 <Grid container spacing={1.5} mb={2.2}><Grid size={{xs:12,md:4}}><StatCard label="Reparaciones" value={String(client.repairs.length)} icon={<ReceiptLongRounded/>}/></Grid><Grid size={{xs:6,md:4}}><StatCard label="Total pagado" value={formatMoney(paid)} icon={<PaymentsRounded/>} tone="success"/></Grid><Grid size={{xs:6,md:4}}><StatCard label="Saldo pendiente" value={formatMoney(pending)} icon={<WalletRounded/>} tone="warning"/></Grid></Grid>
 <Grid container spacing={2.2}><Grid size={{xs:12,lg:4}}><Card><CardContent><Typography variant="h2">Datos del cliente</Typography><Stack spacing={1.5} mt={2}><Info label="Nombre" value={client.name}/><Info label="Teléfono" value={client.phone||'No informado'}/><Info label="Fecha de alta" value={formatDate(client.createdAt)}/><Info label="Última visita" value={newest?formatDate(newest):'Sin visitas'}/></Stack></CardContent></Card></Grid>
 <Grid size={{xs:12,lg:8}}><Card><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}><Box><Typography variant="h2">Historial de reparaciones</Typography><Typography variant="body2" color="text.secondary">Todos los ingresos registrados para este cliente</Typography></Box><Button startIcon={<AddRounded/>} onClick={()=>navigate(newRepair)}>Nueva reparación</Button></Stack>{client.repairs.length?<Stack divider={<Box borderTop="1px solid" borderColor="divider"/>}>{client.repairs.map(repair=><Stack key={repair.id} direction={{xs:'column',sm:'row'}} alignItems={{sm:'center'}} gap={2} py={1.7}><Box flex={1}><Typography fontWeight={750}>#{repair.number} · {repair.deviceBrand} {repair.deviceModel}</Typography><Typography variant="body2" color="text.secondary">{repair.issue} · {formatDate(repair.createdAt)}</Typography></Box><StatusChip status={apiStatus[repair.status]??'received'}/><Typography fontWeight={700}>{formatMoney(repair.total)} · saldo {formatMoney(Math.max(0,repair.total-repair.paid))}</Typography><Button endIcon={<ArrowForwardRounded/>} onClick={()=>navigate(`/admin/reparaciones/${repair.id}`)}>Abrir</Button></Stack>)}</Stack>:<UiState title="Sin reparaciones registradas"/>}</CardContent></Card></Grid></Grid></Box>
}
function Info({label,value}:{label:string;value:string}){return <Box><Typography variant="caption" color="text.secondary">{label}</Typography><Typography fontWeight={700}>{value}</Typography></Box>}
