import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, LinearProgress, Stack, TextField, Typography } from '@mui/material'
import ContentCopyRounded from '@mui/icons-material/ContentCopyRounded'
import axios from 'axios'
import { getBillingPayments, getPlans, getTransferDetails, submitBillingPayment } from './billing.api'
import type { BillingPayment, Plan, PlanCode, TransferDetails } from './billing.types'
import { PlanCards } from './PlanCards'
import { useSubscription } from './SubscriptionContext'
import { formatARS, formatDate } from './billing.utils'
import './billing.scss'

export function SubscriptionPage(){
  const {subscription,refresh}=useSubscription();const[plans,setPlans]=useState<Plan[]>([]);const[payments,setPayments]=useState<BillingPayment[]>([]);const[selected,setSelected]=useState<PlanCode|null>(null);const[details,setDetails]=useState<TransferDetails|null>(null);const[detailsError,setDetailsError]=useState('');const[formOpen,setFormOpen]=useState(false);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');
  const[form,setForm]=useState({reportedAmount:'',payerName:'',transferDate:new Date().toISOString().slice(0,10),reference:'',notes:''});
  const load=()=>Promise.all([getPlans().then(setPlans),getBillingPayments().then(setPayments),refresh()]);useEffect(()=>{void load()},[])
  const plan=plans.find(item=>item.code===selected);const end=subscription?.status==='TRIALING'?subscription.trialEndsAt:subscription?.currentPeriodEnd;
  const statusLabel={TRIALING:'PRUEBA GRATUITA',ACTIVE:'ACTIVA',GRACE:'EN GRACIA',PAST_DUE:'VENCIDA',SUSPENDED:'SUSPENDIDA',CANCELED:'CANCELADA'} as const;
  const usage=useMemo(()=>subscription?.usage,[subscription]);
  const choose=async(code:PlanCode)=>{setSelected(code);setMessage('');try{setDetails(await getTransferDetails());setDetailsError('')}catch(error){setDetails(null);setDetailsError(axios.isAxiosError<{message?:string}>(error)?error.response?.data?.message??'Datos de cobro no disponibles':'Datos de cobro no disponibles')}}
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!selected||!plan)return;setSaving(true);try{await submitBillingPayment({planCode:selected,reportedAmount:Number(form.reportedAmount),payerName:form.payerName,transferDate:form.transferDate,reference:form.reference||undefined,notes:form.notes||undefined});setFormOpen(false);setMessage('Pago informado. Estamos verificando tu transferencia.');await load()}catch{setMessage('No pudimos registrar el pago.')}finally{setSaving(false)}}
  if(!subscription)return <LinearProgress/>;
  return <Box className="billing-page"><Box><Typography variant="h4" fontWeight={900} color="primary.main">Tu plan de TecnoDesk</Typography></Box>{message&&<Alert severity={message.startsWith('Pago informado')?'success':'error'}>{message}</Alert>}
    <section className="billing-summary"><article><small>Plan actual</small><strong>{subscription.status==='TRIALING'?'Plan Completo':subscription.plan.name}</strong></article><article><small>Estado</small><strong>{statusLabel[subscription.status]}</strong></article><article><small>Próximo vencimiento</small><strong>{formatDate(end)}</strong></article><article><small>Días restantes</small><strong>{subscription.daysRemaining}</strong></article></section>
    {subscription.status==='TRIALING'&&<Alert severity="info">Estás disfrutando todas las funciones gratis hasta el {formatDate(subscription.trialEndsAt)}.</Alert>}
    {usage&&<section className="billing-panel billing-usage"><Typography variant="h6" fontWeight={900}>Uso actual</Typography><div className="billing-usage-row"><span>Reparaciones</span><b>{usage.repairs} / {usage.entitlements.repairLimitPerPeriod??'Ilimitadas'}</b></div><div className="billing-usage-row"><span>Seguimientos</span><b>{usage.trackingLinks} / {usage.entitlements.trackingLimitPerPeriod??'Ilimitados'}</b></div></section>}
    <Box><Typography variant="h5" fontWeight={900} mb={3}>{subscription.status==='ACTIVE'?'Renovar o cambiar plan':'Elegí tu plan'}</Typography><PlanCards plans={plans} actionLabel="Pagar por transferencia" onSelect={choose}/></Box>
    {selected&&plan&&<section className="billing-panel"><Typography variant="h5" fontWeight={900}>Realizá la transferencia</Typography><Typography mt={1} mb={2}>{plan.name} · <b>{formatARS(plan.priceARS)}</b></Typography>{detailsError&&<Alert severity="warning">{detailsError}</Alert>}{details&&<><div className="billing-transfer-grid">{[['Titular',details.holderName],['Banco',details.bankName],['Alias',details.alias],['CBU/CVU',details.cbuCvu],['CUIT',details.taxId]].map(([label,value])=><div className="billing-transfer-field" key={label}><small>{label}</small><strong>{value}</strong>{(label==='Alias'||label==='CBU/CVU')&&<Button size="small" startIcon={<ContentCopyRounded/>} onClick={()=>void navigator.clipboard.writeText(value)}>Copiar</Button>}</div>)}</div>{details.additionalText&&<Typography mt={2}>{details.additionalText}</Typography>}<Button variant="contained" size="large" sx={{mt:3}} onClick={()=>{setForm(current=>({...current,reportedAmount:String(plan.priceARS)}));setFormOpen(true)}}>Ya realicé la transferencia</Button></>}</section>}
    <section className="billing-panel"><Typography variant="h6" fontWeight={900} mb={2}>Pagos informados</Typography><div className="billing-payments">{payments.length?payments.map(payment=><article className="billing-payment" key={payment.id}><div><b>{payment.plan.name}</b><Typography variant="body2">Informado el {formatDate(payment.createdAt)}</Typography>{payment.rejectionReason&&<Typography color="error" variant="body2">{payment.rejectionReason}</Typography>}</div><div><b>{formatARS(payment.reportedAmount)}</b><Typography variant="body2">{payment.status==='PENDING'?'Pendiente':payment.status==='APPROVED'?'Aprobado':'Rechazado'}</Typography></div></article>):<Typography color="text.secondary">Todavía no informaste pagos.</Typography>}</div></section>
    <Dialog open={formOpen} onClose={()=>setFormOpen(false)} fullWidth maxWidth="sm"><Box component="form" onSubmit={submit}><DialogTitle>Informar transferencia</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Plan" value={plan?.name??''} disabled/><TextField label="Importe esperado" value={plan?formatARS(plan.priceARS):''} disabled/><TextField required label="Importe transferido" type="number" value={form.reportedAmount} onChange={e=>setForm({...form,reportedAmount:e.target.value})}/><TextField required label="Titular / origen" value={form.payerName} onChange={e=>setForm({...form,payerName:e.target.value})}/><TextField required label="Fecha de transferencia" type="date" InputLabelProps={{shrink:true}} value={form.transferDate} onChange={e=>setForm({...form,transferDate:e.target.value})}/><TextField label="Referencia (opcional)" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/><TextField label="Observación (opcional)" multiline minRows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setFormOpen(false)}>Cancelar</Button><Button type="submit" variant="contained" disabled={saving}>{saving?'Enviando…':'Informar pago'}</Button></DialogActions></Box></Dialog>
  </Box>
}
