import { Alert, MenuItem, TextField } from '@mui/material'
import { useState } from 'react'
import { createCashMovement, type CashMovement } from '../../services/operations'
import { FormDrawer } from '../common/FormDrawer'
import { CurrencyField } from '../common/CurrencyField'

export function NewCashMovementDrawer({ open, onClose, onCreated }: { open: boolean; onClose: () => void; onCreated: (movement: CashMovement) => void }) {
  const [form, setForm] = useState<{type:'INCOME'|'EXPENSE';description:string;amount:number|null;method:NonNullable<CashMovement['method']>}>({ type: 'EXPENSE', description: '', amount: null, method: 'TRANSFER' }), [saving, setSaving] = useState(false), [error, setError] = useState('')
  const save = async () => { if (form.amount == null || form.amount <= 0) return setError(form.amount == null ? 'Ingresá un monto' : 'El monto debe ser mayor que cero'); setSaving(true); setError(''); try { const movement = await createCashMovement({...form,amount:form.amount}); setForm({ type: 'EXPENSE', description: '', amount: null, method: 'TRANSFER' }); onCreated(movement) } catch { setError('No pudimos registrar el movimiento.') } finally { setSaving(false) } }
  return <FormDrawer open={open} eyebrow="CAJA" title="Nuevo movimiento" saving={saving} submitLabel="Registrar movimiento" submitDisabled={!form.description.trim() || form.amount == null || form.amount <= 0} onClose={onClose} onSubmit={() => void save()}>{error && <Alert severity="error">{error}</Alert>}<TextField select label="Tipo" value={form.type} onChange={event => setForm(value => ({ ...value, type: event.target.value as typeof value.type }))}><MenuItem value="INCOME">Ingreso</MenuItem><MenuItem value="EXPENSE">Egreso</MenuItem></TextField><TextField label="Descripción" value={form.description} onChange={event => setForm(value => ({ ...value, description: event.target.value }))}/><CurrencyField required label="Importe" value={form.amount} onValueChange={amount=>setForm(value=>({...value,amount}))} onEmpty={()=>setForm(value=>({...value,amount:null}))} error={Boolean(error)&&form.amount==null} helperText={Boolean(error)&&form.amount==null?'Ingresá un monto':undefined}/><TextField select label="Método" value={form.method} onChange={event => setForm(value => ({ ...value, method: event.target.value as typeof value.method }))}>{[['CASH','Efectivo'],['TRANSFER','Transferencia'],['CARD','Tarjeta'],['OTHER','Otro']].map(option => <MenuItem key={option[0]} value={option[0]}>{option[1]}</MenuItem>)}</TextField></FormDrawer>
}
